# Exercício:

## 01 – Dados as operações abaixo, qual o resultado da operação lógica: 
p and q and r and s and t?
<br>
<br>Como os operadores lógicos podem ser usados para inverter o resultado?

<br>p = 2.0 + 3.0 / 5.0 == 10
<br>q = (p + 10.2) - 5.0 * 2.0 <= 2.9
<br>r = 10 <= p / q + 33.8 < 100
<br>s = 5 != p / (q + r)
<br>t = 33 == s * 2

In [3]:
p = 2.0 + 3.0/5.0 == 10
print(p)
q = (p + 10.2) - 5.0 * 2.0 <= 2.9
print(q)
r = 10 <= p / q + 33.8 < 100
print(r)
s = 5 != p / (q + r)
print(s)
t = 33 == s * 2
print(t)

p and q and r and s and t

False
True
True
True
False

False

In [4]:
#Invertendo o resultado:
not (p and q and r and s and t)

True

## 02 – Usando apenas o operador or, qual seria o resultado final das operações abaixo? Como deve ser usado o not para inverter o resultado?

<br>p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
<br>q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
<br>r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
<br>s = ['a',1,True,'b',0,False] > ['a',True,1]
<br>t = ['a',1,True,'b',0,False] == 1
<br>u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]

In [1]:
#Resultado original:
p = ('a',1,True,'b',0,False) != ('a',True,1,'b',False,0)
print(p)
q = ['a',1,True,'b',0,False] != ('a',True,1,'b',False,0)
print(q)
r = ['a',1,True,'b',0,False] != ['a',True,1,'b',False,0]
print(r)
s = ['a',1,True,'b',0,False] > ['a',True,1]
print(s)
t = ['a',1,True,'b',0,False] == 1
print(t)
u = ['a',True,1] <= ['a',True,1] < ['a',1,True,'b',0,False]
print(u)

False
True
False
True
False
True

In [2]:
resultado_esperado = p or q or r or s or t or u
resultado_esperado

True

In [3]:
#Not
not resultado_esperado

False

## 03 – No exercício 3 da aula 8 foi importado um arquivo .csv para um objeto da classe DataFrame pandas. Importe aqui o mesmo objeto e arredonde e edite o index como realizado no exercício 3 da aula 8. Usando operadores responda, a segunda linha é igual a terceira ou a terceira linha é igual a quarta?

In [4]:
#Recuperação do exercicio 3:
#Carregando pacote
import pandas as pd
import os
#Ver arquivos no diretório
os.listdir()
#Importar o CSV original
DataFrame = pd.read_csv('data_6.csv')
#Criar listas para o dicionário (colunas 1, 4 e 9)
colunas = [DataFrame.iloc[:,0], DataFrame.iloc[:,3], DataFrame.iloc[:,8]]
medias = []
desvios = []
terceiro_quartil = []
for col in colunas:
    medias.append(col.mean())
    desvios.append(col.std())
    terceiro_quartil.append(col.quantile(0.75))

#Dicionário
resultado_dicionario = {
    'medias': medias,
    'desvios': desvios,
    'terceiro_quartil': terceiro_quartil
}
#DataFrame
df_resultado = pd.DataFrame(resultado_dicionario)
#Exportar para CSV
df_resultado.to_csv('resultado_df_dici.csv')
#Ler CSV - índice
df1 = pd.read_csv('resultado_df_dici.csv', index_col='Unnamed: 0')
#Arredondar
df1 = df1.round(3)
print(df1)

        medias       desvios  terceiro_quartil
0   548661.937  2.599129e+05        774252.000
1   731478.007  1.752300e+07             0.000
2  2571004.097  2.036777e+07       1128871.182

In [ ]:
# segunda linha vs terceira
linha2_eq_linha3 = df1.iloc[1].equals(df1.iloc[2])
resultado = linha2_eq_linha3 or False
print("Resultado da comparação:", resultado)

Resultado da comparação: False

## 04 – Usando operadores verifique se todos os valores contidos na primeira linha são maiores ou iguais a 10.

In [ ]:
linha1 = df1.iloc[0]
resultado = (linha1 >= 10).all()
print(resultado)

True

## 05 – Usando operadores verifique se todos os valores contidos na terceira coluna estão entre 0 inclusive e 40.

In [7]:
coluna3 = df1.iloc[:, 2]
resultado = ((coluna3 >= 0) & (coluna3 <= 40)).all()
print(resultado)

False

## 06 – Usando operadores verifique se algum dos valores contidos na última linha está acima de 10.

In [ ]:
ultima_linha = df1.iloc[-1] 
resultado = (ultima_linha > 10).any()
print(resultado)

True

## 07 – Recupere a DataFrame contendo apenas valores que estejam acima de 5 e abaixo de 7.

In [ ]:
df_filtrado = df1.where((df1 > 5) & (df1 < 7)) #.where (mantém os valores da condição e substitui po NAN aquele que não)
df_filtrado

   medias  desvios  terceiro_quartil
0     NaN      NaN               NaN
1     NaN      NaN               NaN
2     NaN      NaN               NaN

## 08 – Recupere a DataFrame contendo apenas valores que estejam abaixo de 5 inclusive ou acima de 7.

In [15]:
df_filtrado1 = df1.where((df1 <= 5) | (df1 > 7))
df_filtrado1

        medias       desvios  terceiro_quartil
0   548661.937  2.599129e+05        774252.000
1   731478.007  1.752300e+07             0.000
2  2571004.097  2.036777e+07       1128871.182

## 09 – Converta as duas últimas colunas do objeto DataFrame para dois objetos da classe numpy array. Algum dos valores contidos no primeiro array estão entre 2 inclusive e 5 inclusive?

In [ ]:
import numpy as np
ultimas_colunas = df1.iloc[:, -2:] #iloc[:, -2:] (pega as 2 últimas colunas)
array1 = ultimas_colunas.iloc[:, 0].to_numpy() #to_numpy() (converte para array numpy)
print(array1)
array2 = ultimas_colunas.iloc[:, 1].to_numpy()
print(array2)
resultado = ((array1 >= 2) & (array1 <= 5)).any() #(array1 >= 2) & (array1 <= 5) (intervalos) + .any() (verifica se existe pelo menos um valor)
print(resultado)

[  259912.926 17523003.588 20367766.569]
[ 774252.          0.    1128871.182]
False

## 10 – Os valores contidos nos dois arrays são superiores à -1 e inferiores à 12?

In [ ]:
cond1_array = ((array1 > -1) & (array1 < 12)).all() #> -1 e < 12 (intervalo)
cond2_array = ((array2 > -1) & (array2 < 12)).all() #.all() (verifica se todos os valores atendem)
resultado1 = cond1_array and cond2_array  #and (ambos arrays precisam satisfazer)
print(resultado1)

False