In [ ]:
num_1 = 4
num_2 = 2
print(num_1+num_2)
print(num_1-num_2)
print(num_1%num_2)
print(num_1//num_2)
print(num_1/num_2)

6
2
0
2

In [ ]:
tupla1 = (1, 2, 3)
tupla2 = (1, 2, 3)
print(tupla1 == tupla2) #verificação geral mas numero por numero
print(tupla1 + tupla2) #concatenar
#print(tupla1 * tupla2) #não conseguimos multiplicar tuplas 

tupla1 += tupla2
display(tupla1)
display(tupla2) 
help(display)
lista_tupla1 = list(tupla1) #transformar em lista 
#lista_tupla1 += 2 #não conseguimos somar inteiro em lista
lista_tupla1 += tupla1 #conseguimos somar tupla com lista
lista_tupla1 
lista_tupla1[2] += 2 #[qual valor da tupla será somado, assim, podemos fazer a soma com numero inteiro mas com apenas com lista]
lista_tupla1

True
(1, 2, 3, 1, 2, 3)

(1, 2, 3, 1, 2, 3)

(1, 2, 3)

Help on function display in module IPython.core.display_functions:

display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)
    Display a Python object in all frontends.

    By default all representations will be computed and sent to the frontends.
    Frontends can decide which representation is used and how.

    In terminal IPython this will be similar to using :func:`print`, for use in richer
    frontends see Jupyter notebook examples with rich display logic.

    Parameters
    ----------
    *objs : object
        The Python objects to display.
    raw : bool, optional
        Are the objects to be displayed already mimetype-keyed dicts of raw display data,
        or Python objects that need to be formatted before display? [default: False]
    include : list, tuple or set, optional
        A list of format type strings (MIME types) to include in the
        format data dict. If this is set *only* the format types included
        in this list will be computed.
    exclude : list, tuple or set, optional
        A list of format type strings (MIME types) to exclude in the format
        data dict. If this is set all format types will be computed,
        except for those included in this argument.
    metadata : dict, optional
        A dictionary of metadata to associate with the output.
        mime-type keys in this dictionary will be associated with the individual
        representation formats, if they exist.
    transient : dict, optional
        A dictionary of transient data to associate with the output.
        Data in this dict should not be persisted to files (e.g. notebooks).
    display_id : str, bool optional
        Set an id for the display.
        This id can be used for updating this display area later via update_display.
        If given as `True`, generate a new `display_id`
    clear : bool, optional
        Should the output area be cleared before displaying anything? If True,
        this will wait for additional output before clearing. [default: False]
    **kwargs : additional keyword-args, optional
        Additional keyword-arguments are passed through to the display publisher.

    Returns
    -------
    handle: DisplayHandle
        Returns a handle on updatable displays for use with :func:`update_display`,
        if `display_id` is given. Returns :any:`None` if no `display_id` is given
        (default).

    Examples
    --------
    >>> class Json(object):
    ...     def __init__(self, json):
    ...         self.json = json
    ...     def _repr_pretty_(self, pp, cycle):
    ...         import json
    ...         pp.text(json.dumps(self.json, indent=2))
    ...     def __repr__(self):
    ...         return str(self.json)
    ...

    >>> d = Json({1:2, 3: {4:5}})

    >>> print(d)
    {1: 2, 3: {4: 5}}

    >>> display(d)
    {
      "1": 2,
      "3": {
        "4": 5
      }
    }

    >>> def int_formatter(integer, pp, cycle):
    ...     pp.text('I'*integer)

    >>> plain = get_ipython().display_formatter.formatters['text/plain']
    >>> plain.for_type(int, int_formatter)
    <function _repr_pprint at 0x...>
    >>> display(7-5)
    II

    >>> del plain.type_printers[int]
    >>> display(7-5)
    2

    See Also
    --------
    :func:`update_display`

    Notes
    -----
    In Python, objects can declare their textual representation using the
    `__repr__` method. IPython expands on this idea and allows objects to declare
    other, rich representations including:

      - HTML
      - JSON
      - PNG
      - JPEG
      - SVG
      - LaTeX

    A single object can declare some or all of these representations; all are
    handled by IPython's display system.

    The main idea of the first approach is that you have to implement special
    display methods when you define your class, one for each representation you
    want to use. Here is a list of the names of the special methods and the
    values they must return:

      - `_repr_html_`: return raw HTML as a string, or a tuple (see below).
      - `_repr_json_`: return a JSONable dict, or a tuple (see below).
      - `_repr_jpeg_`: return raw JPEG data, or a tuple (see below).
      - `_repr_png_`: return raw PNG data, or a tuple (see below).
      - `_repr_svg_`: return raw SVG data as a string, or a tuple (see below).
      - `_repr_latex_`: return LaTeX commands in a string surrounded by "$",
                        or a tuple (see below).
      - `_repr_mimebundle_`: return a full mimebundle containing the mapping
                             from all mimetypes to data.
                             Use this for any mime-type not listed above.

    The above functions may also return the object's metadata alonside the
    data.  If the metadata is available, the functions will return a tuple
    containing the data and metadata, in that order.  If there is no metadata
    available, then the functions will return the data only.

    When you are directly writing your own classes, you can adapt them for
    display in IPython by following the above approach. But in practice, you
    often need to work with existing classes that you can't easily modify.

    You can refer to the documentation on integrating with the display system in
    order to register custom formatters for already existing types
    (:ref:`integrating_rich_display`).

    .. versionadded:: 5.4 display available without import
    .. versionadded:: 6.1 display available without import

    Since IPython 5.4 and 6.1 :func:`display` is automatically made available to
    the user without import. If you are using display in a document that might
    be used in a pure python context or with older version of IPython, use the
    following import at the top of your file::

        from IPython.display import display

[1, 2, 5, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
dici1 = {"a": 1, "b": 2, "c":5}
dici2 = {"a": 10, "b": 20}
#dici1 + dici2 --> não podemos somar dicionarios porque sesu valores são definidos manualmente
dici1.update(dici2) #atualiza os elementos que não tem em um dicionario no outro 
dici1

{'a': 10, 'b': 20, 'c': 5}

In [54]:
import numpy as np

In [ ]:
array = numpy.array(lista_tupla1)
print(array)
array +=2 #conseguimos somar inteiro no array por que cada valor vai ser independente 
print(array)
array *= array 
print(array)

[1 2 5 1 2 3 1 2 3 1 2 3]
[3 4 7 3 4 5 3 4 5 3 4 5]
[ 9 16 49  9 16 25  9 16 25  9 16 25]

In [ ]:
numpy.insert(arr=array, obj=2, values= 100) #definição de posição e objeto para a inserção de um valor no array e não aceita em mais de uma posição mas aceita mais de um valor
numpy.insert(arr=array, obj=2, values= (2,5)) #definição de posição e objeto para a inserção de um valor no array e não aceita em mais de uma posição mas aceita mais de um valor
lista_tupla1[2] = 100
lista_tupla1 #aqui em lista ele substitui o valor

array([ 9, 16,  2,  5, 49,  9, 16, 25,  9, 16, 25,  9, 16, 25])

In [ ]:
array = numpy.array(lista_tupla1).reshape(6,-1) #organizar as colunas e linhas quando só em linhas ou colunas (o -1 ignora a quantidade de coluna ou de linha e leva em consideração apenas o outro valor)
array.shape
array

array([[  1,   2],
       [100,   1],
       [  2,   3],
       [  1,   2],
       [  3,   1],
       [  2,   3]])

In [ ]:
import pandas

In [51]:
df = pandas.DataFrame(array)
df

     0  1
0    1  2
1  100  1
2    2  3
3    1  2
4    3  1
5    2  3

In [ ]:
df += df #soma de df item por item
df
array_ones = np.zeros_like(df) #zerar todos os itens
array_ones[1,1] = 100  #definição de posição quem eu quero e o valor que quero
array_ones

array([[  0,   0],
       [  0, 100],
       [  0,   0],
       [  0,   0],
       [  0,   0],
       [  0,   0]])

In [ ]:
print("Py" != "Py")
print(1 == 1)
print(2 >= 2.01)
print(5<8)
print(4 <= 5 <7)

False
True
False
True
True

In [67]:
import numpy as np
import pandas as pd

In [ ]:
print((1,2) == (1.0, 2.0)) #mesmo conteudo e classe
print((1,2) == {1.0, 2.0}) #mesmo conteudo mas classes diferentes
print((1,2) <= (1.0, 2.0)) 
print((1,2) < (1.0, 2.0)) 
print((1,2) == (1.0, 2.0)) 
print((1,2) == (1.0, 2.0)) 
print({'a': 1, 'b': 2} == {'a': 1}) #dicionario quando iguais são verdadeiro, mas quando com um elemento diferente falso para igualdade
#".values" --> volta o valor 
#".keys" --> volta as chaves
#".items" --> volta ambos

True
False
True
False
True
True
False

In [90]:
array = np.random.normal(0, 1, 10).reshape(10,-1) #distribuição normal com média, desvio padrão, com x elementos
print(array.shape)
print(array)
print(array[:2])

(10, 1)
[[ 0.74248862]
 [ 0.03242238]
 [-0.29567981]
 [ 0.10491585]
 [ 0.62661734]
 [-1.17103073]
 [-0.56628182]
 [ 0.56684484]
 [-0.43813979]
 [ 0.69734057]]
[[0.74248862]
 [0.03242238]]

In [97]:
array = np.random.normal(0, 1, 10).reshape(10,-1) 
array2 = np.random.normal(0, 1, 10).reshape(10,-1) 
array == array2 
#para setar os valores randomizados:
np.random.seed(42) #variável global
array1 = np.random.normal(0, 1, 10).reshape(10,-1) 
array3 = np.random.normal(0, 1, 10).reshape(10,-1) 
print(array1[:2])
print(array2[:2])

[[ 0.49671415]
 [-0.1382643 ]]
[[-0.60170661]
 [ 1.85227818]]

In [101]:
pd.DataFrame(array) == pd.DataFrame(array)

      0
0  True
1  True
2  True
3  True
4  True
5  True
6  True
7  True
8  True
9  True

In [104]:
df1 = pd.DataFrame(array1)
df2 = pd.DataFrame(array2)
df1.head()

          0
0  0.496714
1 -0.138264
2  0.647689
3  1.523030
4 -0.234153

In [110]:
print(1 == 1 and 1 == 1)
print(1 == 1 and 1 == 5)
print(1 == 1 and 1 == 1)
print(1 == 1 or 1 == 1)
print(1 == 1 or 1 == 5)

True
False
True
True
True

In [111]:
print(True and not True)
print(True or True)
print(False or True)
print(True and False)
print(True is False)
print(False is not True)

False
True
True
False
False
True

In [ ]:
p = 1
q = r 
r = 0
print(p == q and p == r)
print(p == q or p == r)

False
False

In [120]:
print(1 in [1, 2, 3, 4, 5]) #in funciona para o que esta dentro do que 
print(p is r)
print(r is not q)
print(q is r)
print(q is not p)

True
False
False
True
True