In [2]:
import pandas as pd
import os

In [3]:
os.listdir()

['.git',
 '.venv',
 '.venv-1',
 '02 - introdução.ipynb',
 '04 - objetos_simples.ipynb',
 '05-Objetos_Compostos_1.ipynb',
 '06-Objetos_Compostos_2.ipynb',
 '07-Operadores_aritméticos_2026-03-23.ipynb',
 '08-Operadores_relacionais_2026-03-24.ipynb',
 '09-Operadores_lógicos_2026-03-25.ipynb',
 '1-s2.0-S0039914017303983-main.pdf',
 '10-Estruturas_condicionais_2026-03-26.ipynb',
 'aula1_note.ipynb',
 'aula2_note.ipynb',
 'aula3_note.ipynb',
 'aula4_1_note.ipynb',
 'aula4_2_note.ipynb',
 'aula4_note.ipynb',
 'aula5_1_note.ipynb',
 'aula5_note.ipynb',
 'aulaextra.ipynb',
 'data_variable_edit.csv',
 'praticaaula2.ipynb',
 'primeiro_note.ipynb',
 'segundo_note.ipynb']

In [4]:
df = pd.read_csv('data_variable_edit.csv')
df.head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [5]:
df.tail()

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360 Cells Treatment
175  Sample 2      0.45     0.45    0.45     0.45   CD8      Mock
176  Sample 3      0.58     0.58    0.58     0.58   CD8      Mock
177  Sample 4      0.76     0.76    0.76     0.76   CD8      Mock
178  Sample 5      0.60     0.60    0.60     0.60   CD8      Mock
179  Sample 6      0.65     0.65    0.65     0.65   CD8      Mock

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Sample     180 non-null    object
 1   DV1 BR90   180 non-null    float64
 2   DV2 265    180 non-null    float64
 3   DV3 98     180 non-null    float64
 4   DV4 360    180 non-null    float64
 5   Cells      180 non-null    object
 6   Treatment  180 non-null    object
dtypes: float64(4), object(3)
memory usage: 10.0+ KB

In [7]:
df.describe()

         DV1 BR90     DV2 265      DV3 98     DV4 360
count  180.000000  180.000000  180.000000  180.000000
mean     7.263833    7.413167    9.108333    6.624167
std     10.454712   10.944008   13.001236   10.534487
min      0.110000    0.110000    0.080000    0.010000
25%      1.387500    1.357500    1.067500    0.835000
50%      2.790000    2.595000    3.390000    1.970000
75%      6.900000    7.765000   12.047500    6.150000
max     52.380000   53.190000   81.420000   50.880000

In [8]:
df.select_dtypes(include='object').head()

     Sample         Cells  Treatment
0  Sample 1  CD4/CD8/CD19  Untreated
1  Sample 2  CD4/CD8/CD19  Untreated
2  Sample 3  CD4/CD8/CD19  Untreated
3  Sample 4  CD4/CD8/CD19  Untreated
4  Sample 5  CD4/CD8/CD19  Untreated

In [9]:
df.select_dtypes(exclude='number').describe()

          Sample         Cells  Treatment
count        180           180        180
unique         6             6          5
top     Sample 1  CD4/CD8/CD19  Untreated
freq          30            30         36

In [10]:
df['Sample']

0      Sample 1
1      Sample 2
2      Sample 3
3      Sample 4
4      Sample 5
         ...
175    Sample 2
176    Sample 3
177    Sample 4
178    Sample 5
179    Sample 6
Name: Sample, Length: 180, dtype: object

In [11]:
len(df[df['Sample'] == "Sample_1"])

0

In [12]:
df.query('Sample == "Sample 1"')

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
6    Sample 1     23.44    19.50   27.48    25.89       CD4/CD8  Untreated
12   Sample 1      4.23     4.10   17.12     6.18          CD14  Untreated
18   Sample 1     20.00    19.02   51.24    21.21          CD19  Untreated
24   Sample 1      6.65     3.24    9.12     7.16           CD4  Untreated
30   Sample 1     18.20    17.60   22.33    20.32           CD8  Untreated
36   Sample 1     18.54    16.09   35.69    20.24  CD4/CD8/CD19       5 ug
42   Sample 1     13.40    11.20   16.03    14.80       CD4/CD8       5 ug
48   Sample 1      1.97     1.91    6.24     2.88          CD14       5 ug
54   Sample 1      4.89     4.65   18.67     5.18          CD19       5 ug
60   Sample 1      3.69     1.80    5.07     3.98           CD4       5 ug
66   Sample 1     10.11     9.78   12.41    11.29           CD8       5 ug
72   Sample 1      7.26     5.14   18.91     3.52  CD4/CD8/CD19      10 ug
78   Sample 1      4.73     2.73    0.78     0.85       CD4/CD8      10 ug
84   Sample 1      1.35     1.30    4.91     1.97          CD14      10 ug
90   Sample 1      2.41     2.30   18.68     2.56          CD19      10 ug
96   Sample 1      1.23     0.48    0.17     0.03           CD4      10 ug
102  Sample 1      3.72     2.46    0.42     1.08           CD8      10 ug
108  Sample 1      3.18     4.01    1.34     1.43  CD4/CD8/CD19      20 ug
114  Sample 1      1.74     2.57    0.13     0.01       CD4/CD8      20 ug
120  Sample 1      1.49     1.49    3.82     1.49          CD14      20 ug
126  Sample 1      1.38     1.38    1.44     1.38          CD19      20 ug
132  Sample 1      1.39     1.98    0.10     0.03           CD4      20 ug
138  Sample 1      0.52     0.76    0.08     0.13           CD8      20 ug
144  Sample 1      3.18     3.13    3.33     3.23  CD4/CD8/CD19       Mock
150  Sample 1      1.94     1.94    1.89     1.91       CD4/CD8       Mock
156  Sample 1      0.92     0.89    1.49     1.34          CD14       Mock
162  Sample 1      1.19     1.14    1.38     1.27          CD19       Mock
168  Sample 1      0.80     0.80    0.80     0.80           CD4       Mock
174  Sample 1      1.26     1.26    1.26     1.26           CD8       Mock

In [16]:
df1 = df.query('Cells == "CD4/CD8/CD19" and Sample == "Sample1"')
print(df1)

Empty DataFrame
Columns: [Sample, DV1 BR90, DV2 265, DV3 98, DV4 360, Cells, Treatment]
Index: []

In [20]:
print(df[['Cells', 'Sample']])
print(df.loc[:2,['Cells', 'Sample']])

            Cells    Sample
0    CD4/CD8/CD19  Sample 1
1    CD4/CD8/CD19  Sample 2
2    CD4/CD8/CD19  Sample 3
3    CD4/CD8/CD19  Sample 4
4    CD4/CD8/CD19  Sample 5
..            ...       ...
175           CD8  Sample 2
176           CD8  Sample 3
177           CD8  Sample 4
178           CD8  Sample 5
179           CD8  Sample 6

[180 rows x 2 columns]
          Cells    Sample
0  CD4/CD8/CD19  Sample 1
1  CD4/CD8/CD19  Sample 2
2  CD4/CD8/CD19  Sample 3

In [21]:
df.loc[::-1]

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
179  Sample 6      0.65     0.65    0.65     0.65           CD8       Mock
178  Sample 5      0.60     0.60    0.60     0.60           CD8       Mock
177  Sample 4      0.76     0.76    0.76     0.76           CD8       Mock
176  Sample 3      0.58     0.58    0.58     0.58           CD8       Mock
175  Sample 2      0.45     0.45    0.45     0.45           CD8       Mock
..        ...       ...      ...     ...      ...           ...        ...
4    Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated
3    Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
2    Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
1    Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated

[180 rows x 7 columns]

In [24]:
df[df.columns[1:5]].head()

   DV1 BR90  DV2 265  DV3 98  DV4 360
0     44.54    39.56   81.42    48.23
1     52.17    52.71   52.13    49.19
2     45.37    52.28   42.48    50.88
3     52.38    52.49   58.69    38.85
4     49.51    51.85   51.10    47.40

In [27]:
df[df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8'])].head()

     Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0  Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1  Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2  Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3  Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4  Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated

In [30]:
~df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8']).head()

0    False
1    False
2    False
3    False
4    False
Name: Cells, dtype: bool

In [31]:
df[df.columns[-2]].isin(['CD4/CD8/CD19', 'CD4/CD8']).head()

0    True
1    True
2    True
3    True
4    True
Name: Cells, dtype: bool

In [32]:
df.value_counts()

Sample    DV1 BR90  DV2 265  DV3 98  DV4 360  Cells         Treatment
Sample 1  0.52      0.76     0.08    0.13     CD8           20 ug        1
          0.80      0.80     0.80    0.80     CD4           Mock         1
          0.92      0.89     1.49    1.34     CD14          Mock         1
          1.19      1.14     1.38    1.27     CD19          Mock         1
          1.23      0.48     0.17    0.03     CD4           10 ug        1
                                                                        ..
Sample 6  17.62     18.79    22.22   17.09    CD4/CD8/CD19  5 ug         1
          21.78     21.45    16.03   16.96    CD19          Untreated    1
          22.44     25.04    27.88   24.45    CD8           Untreated    1
          27.19     30.55    33.96   28.91    CD4/CD8       Untreated    1
          50.16     53.19    50.76   46.78    CD4/CD8/CD19  Untreated    1
Name: count, Length: 180, dtype: int64

In [34]:
df.sort_index(ascending=True)

       Sample  DV1 BR90  DV2 265  DV3 98  DV4 360         Cells  Treatment
0    Sample 1     44.54    39.56   81.42    48.23  CD4/CD8/CD19  Untreated
1    Sample 2     52.17    52.71   52.13    49.19  CD4/CD8/CD19  Untreated
2    Sample 3     45.37    52.28   42.48    50.88  CD4/CD8/CD19  Untreated
3    Sample 4     52.38    52.49   58.69    38.85  CD4/CD8/CD19  Untreated
4    Sample 5     49.51    51.85   51.10    47.40  CD4/CD8/CD19  Untreated
..        ...       ...      ...     ...      ...           ...        ...
175  Sample 2      0.45     0.45    0.45     0.45           CD8       Mock
176  Sample 3      0.58     0.58    0.58     0.58           CD8       Mock
177  Sample 4      0.76     0.76    0.76     0.76           CD8       Mock
178  Sample 5      0.60     0.60    0.60     0.60           CD8       Mock
179  Sample 6      0.65     0.65    0.65     0.65           CD8       Mock

[180 rows x 7 columns]

In [36]:
df.sort_values(by='Cells').value_counts('Cells')

Cells
CD14            30
CD19            30
CD4             30
CD4/CD8         30
CD4/CD8/CD19    30
CD8             30
Name: count, dtype: int64

In [39]:
df['DV1 BR90'].nlargest(5)

3    52.38
1    52.17
5    50.16
4    49.51
2    45.37
Name: DV1 BR90, dtype: float64

In [43]:
df[[df.columns[1], df.columns[1]]].nlargest(5, columns=def.columns[1])

SyntaxError: invalid syntax (1563980138.py, line 1)

In [41]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
Sample,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,...,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6
DV1 BR90,44.54,52.17,45.37,52.38,49.51,50.16,23.44,25.76,29.13,25.75,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV2 265,39.56,52.71,52.28,52.49,51.85,53.19,19.5,26.92,35.21,26.92,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV3 98,81.42,52.13,42.48,58.69,51.1,50.76,27.48,32.45,36.23,32.06,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV4 360,48.23,49.19,50.88,38.85,47.4,46.78,25.89,27.97,29.84,28.35,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
Cells,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8,CD4/CD8,CD4/CD8,CD4/CD8,...,CD4,CD4,CD4,CD4,CD8,CD8,CD8,CD8,CD8,CD8
Treatment,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,...,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock

In [42]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,170,171,172,173,174,175,176,177,178,179
Sample,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,...,Sample 3,Sample 4,Sample 5,Sample 6,Sample 1,Sample 2,Sample 3,Sample 4,Sample 5,Sample 6
DV1 BR90,44.54,52.17,45.37,52.38,49.51,50.16,23.44,25.76,29.13,25.75,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV2 265,39.56,52.71,52.28,52.49,51.85,53.19,19.5,26.92,35.21,26.92,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV3 98,81.42,52.13,42.48,58.69,51.1,50.76,27.48,32.45,36.23,32.06,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
DV4 360,48.23,49.19,50.88,38.85,47.4,46.78,25.89,27.97,29.84,28.35,...,0.88,0.6,0.53,0.67,1.26,0.45,0.58,0.76,0.6,0.65
Cells,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8/CD19,CD4/CD8,CD4/CD8,CD4/CD8,CD4/CD8,...,CD4,CD4,CD4,CD4,CD8,CD8,CD8,CD8,CD8,CD8
Treatment,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,Untreated,...,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock,Mock

In [45]:
df['Treatment'].value_counts()

Treatment
Untreated    36
5 ug         36
10 ug        36
20 ug        36
Mock         36
Name: count, dtype: int64

In [47]:
pd.get_dummies(df['Treatment'])

     10 ug  20 ug   5 ug   Mock  Untreated
0    False  False  False  False       True
1    False  False  False  False       True
2    False  False  False  False       True
3    False  False  False  False       True
4    False  False  False  False       True
..     ...    ...    ...    ...        ...
175  False  False  False   True      False
176  False  False  False   True      False
177  False  False  False   True      False
178  False  False  False   True      False
179  False  False  False   True      False

[180 rows x 5 columns]

In [48]:
df.value_counts().to_frame()

                                                                 count
Sample   DV1 BR90 DV2 265 DV3 98 DV4 360 Cells        Treatment
Sample 1 0.52     0.76    0.08   0.13    CD8          20 ug          1
         0.80     0.80    0.80   0.80    CD4          Mock           1
         0.92     0.89    1.49   1.34    CD14         Mock           1
         1.19     1.14    1.38   1.27    CD19         Mock           1
         1.23     0.48    0.17   0.03    CD4          10 ug          1
...                                                                ...
Sample 6 17.62    18.79   22.22  17.09   CD4/CD8/CD19 5 ug           1
         21.78    21.45   16.03  16.96   CD19         Untreated      1
         22.44    25.04   27.88  24.45   CD8          Untreated      1
         27.19    30.55   33.96  28.91   CD4/CD8      Untreated      1
         50.16    53.19   50.76  46.78   CD4/CD8/CD19 Untreated      1

[180 rows x 1 columns]

In [49]:
coluna1 = df.columns[0]
coluna2 = df.columns[-1]
print(coluna1, coluna2)

Sample Treatment

In [53]:
display(
    df.value_counts([
        coluna1,
        coluna2
    ])
    .to_frame()
    .rename(columns={0: 'Freq Abso Simp'})
    .sort_index()
)

                    count
Sample   Treatment
Sample 1 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 2 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 3 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 4 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 5 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6
Sample 6 10 ug          6
         20 ug          6
         5 ug           6
         Mock           6
         Untreated      6

In [55]:
df.groupby('Cells').sum()

,Sample,DV1 BR90,DV2 265,DV3 98,DV4 360,Treatment
Cells,,,,,,
CD14,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,64.31,54.24,150.46,64.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD19,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,192.37,188.63,278.12,160.54,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,76.95,73.17,79.47,58.43,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,277.77,292.89,300.59,261.84,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8/CD19,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,480.33,491.61,588.66,430.64,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD8,Sample 1Sample 2Sample 3Sample 4Sample 5Sample...,215.76,233.83,242.20,216.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...

In [57]:
coluna = [1, 2, 3, 4, 5, 6]
df.iloc[:, coluna].groupby("Cells").sum()

,DV1 BR90,DV2 265,DV3 98,DV4 360,Treatment
Cells,,,,,
CD14,64.31,54.24,150.46,64.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD19,192.37,188.63,278.12,160.54,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4,76.95,73.17,79.47,58.43,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8,277.77,292.89,300.59,261.84,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD4/CD8/CD19,480.33,491.61,588.66,430.64,UntreatedUntreatedUntreatedUntreatedUntreatedU...
CD8,215.76,233.83,242.20,216.45,UntreatedUntreatedUntreatedUntreatedUntreatedU...